# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "google_hash"
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rogerdpack"]
  s.date = "2014-02-19"
  s.description = "Ruby wrappers to the google hash library"
  s.email = "rogerdpack@gmail.com"
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README",
    "TODO",
    "changelog"
  ]
  s.files = [
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "changelog",
    "ext/clean.bat",
    "ext/extconf.rb",
    "ext/go.bat",
    "ext/sparsehash-1.8.1/AUTHORS",
    "ext/sparsehash-1.8.1/COPYING",
    "ext/sparsehash-1.8.1/ChangeLog",
    "ext/sparsehash-1.8.1/INSTALL",
    "ext/sparsehash-1.8.1/Makefile.am",
    "ext/sparsehash-1.8.1/Makefile.in",
    "ext/sparsehash-1.8.1/NEWS",
    "ext/sparsehash-1.8.1/README",
    "ext/sparsehash-1.8.1/README_windows.txt",
    "ext/sparsehash-1.8.1/TODO",
    "ext/sparsehash-1.8.1/aclocal.m4",
    "ext/sparsehash-1.8.1/compile",
    "ext/sparsehash-1.8.1/config.guess",
    "ext/sparsehash-1.8.1/config.sub",
    "ext/sparsehash-1.8.1/configure",
    "ext/sparsehash-1.8.1/configure.ac",
    "ext/sparsehash-1.8.1/depcomp",
    "ext/sparsehash-1.8.1/doc/dense_hash_map.html",
    "ext/sparsehash-1.8.1/doc/dense_hash_set.html",
    "ext/sparsehash-1.8.1/doc/designstyle.css",
    "ext/sparsehash-1.8.1/doc/implementation.html",
    "ext/sparsehash-1.8.1/doc/index.html",
    "ext/sparsehash-1.8.1/doc/performance.html",
    "ext/sparsehash-1.8.1/doc/sparse_hash_map.html",
    "ext/sparsehash-1.8.1/doc/sparse_hash_set.html",
    "ext/sparsehash-1.8.1/doc/sparsetable.html",
    "ext/sparsehash-1.8.1/experimental/Makefile",
    "ext/sparsehash-1.8.1/experimental/README",
    "ext/sparsehash-1.8.1/experimental/example.c",
    "ext/sparsehash-1.8.1/experimental/libchash.c",
    "ext/sparsehash-1.8.1/experimental/libchash.h",
    "ext/sparsehash-1.8.1/google-sparsehash.sln",
    "ext/sparsehash-1.8.1/install-sh",
    "ext/sparsehash-1.8.1/m4/acx_pthread.m4",
    "ext/sparsehash-1.8.1/m4/google_namespace.m4",
    "ext/sparsehash-1.8.1/m4/namespaces.m4",
    "ext/sparsehash-1.8.1/m4/stl_hash.m4",
    "ext/sparsehash-1.8.1/m4/stl_hash_fun.m4",
    "ext/sparsehash-1.8.1/m4/stl_namespace.m4",
    "ext/sparsehash-1.8.1/missing",
    "ext/sparsehash-1.8.1/mkinstalldirs",
    "ext/sparsehash-1.8.1/packages/deb.sh",
    "ext/sparsehash-1.8.1/packages/deb/README",
    "ext/sparsehash-1.8.1/packages/deb/changelog",
    "ext/sparsehash-1.8.1/packages/deb/compat",
    "ext/sparsehash-1.8.1/packages/deb/control",
    "ext/sparsehash-1.8.1/packages/deb/copyright",
    "ext/sparsehash-1.8.1/packages/deb/docs",
    "ext/sparsehash-1.8.1/packages/deb/rules",
    "ext/sparsehash-1.8.1/packages/deb/sparsehash.dirs",
    "ext/sparsehash-1.8.1/packages/deb/sparsehash.install",
    "ext/sparsehash-1.8.1/packages/rpm.sh",
    "ext/sparsehash-1.8.1/packages/rpm/rpm.spec",
    "ext/sparsehash-1.8.1/src/config.h.in",
    "ext/sparsehash-1.8.1/src/config.h.include",
    "ext/sparsehash-1.8.1/src/google/dense_hash_map",
    "ext/sparsehash-1.8.1/src/google/dense_hash_set",
    "ext/sparsehash-1.8.1/src/google/sparse_hash_map",
    "ext/sparsehash-1.8.1/src/google/sparse_hash_set",
    "ext/sparsehash-1.8.1/src/google/sparsehash/densehashtable.h",
    "ext/sparsehash-1.8.1/src/google/sparsehash/hashtable-common.h",
    "ext/sparsehash-1.8.1/src/google/sparsehash/libc_allocator_with_realloc.h",
    "ext/sparsehash-1.8.1/src/google/sparsehash/sparsehashtable.h",
    "ext/sparsehash-1.8.1/src/google/sparsetable",
    "ext/sparsehash-1.8.1/src/google/type_traits.h",
    "ext/sparsehash-1.8.1/src/hash_test_interface.h",
    "ext/sparsehash-1.8.1/src/hashtable_test.cc",
    "ext/sparsehash-1.8.1/src/libc_allocator_with_realloc_test.cc",
    "ext/sparsehash-1.8.1/src/simple_test.cc",
    "ext/sparsehash-1.8.1/src/sparsetable_unittest.cc",
    "ext/sparsehash-1.8.1/src/testutil.h",
    "ext/sparsehash-1.8.1/src/time_hash_map.cc",
    "ext/sparsehash-1.8.1/src/type_traits_unittest.cc",
    "ext/sparsehash-1.8.1/src/windows/config.h",
    "ext/sparsehash-1.8.1/src/windows/google/sparsehash/sparseconfig.h",
    "ext/sparsehash-1.8.1/src/windows/port.cc",
    "ext/sparsehash-1.8.1/src/windows/port.h",
    "ext/sparsehash-1.8.1/vsprojects/hashtable_test/hashtable_test.vcproj",
    "ext/sparsehash-1.8.1/vsprojects/simple_test/simple_test.vcproj",
    "ext/sparsehash-1.8.1/vsprojects/sparsetable_unittest/sparsetable_unittest.vcproj",
    "ext/sparsehash-1.8.1/vsprojects/time_hash_map/time_hash_map.vcproj",
    "ext/sparsehash-1.8.1/vsprojects/type_traits_unittest/type_traits_unittest.vcproj",
    "ext/spec.bat",
    "ext/template/google_hash.cpp.erb",
    "ext/template/main.cpp.erb",
    "results.txt",
    "spec/bench_gc.rb",
    "spec/benchmark.rb",
    "spec/scale.rb",
    "spec/spec.google_hash.rb",
    "to_build_locally_run_ext_go_bat"
  ]
  s.homepage = "http://github.com/rdp/ruby_google_hash"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby wrappers to the google hash library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sane>, [">= 0"])
      s.add_development_dependency(%q<hitimes>, [">= 0"])
    else
      s.add_dependency(%q<sane>, [">= 0"])
      s.add_dependency(%q<hitimes>, [">= 0"])
    end
  else
    s.add_dependency(%q<sane>, [">= 0"])
    s.add_dependency(%q<hitimes>, [">= 0"])
  end
end

