# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "google_hash"
  s.version = "0.8.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rogerdpack"]
  s.date = "2014-05-26"
  s.description = "Ruby wrappers to the google hash library"
  s.email = "rogerdpack@gmail.com"
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "ChangeLog.txt",
    "README",
    "TODO"
  ]
  s.files = [
    "ChangeLog.txt",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "ext/clean.bat",
    "ext/clean.sh",
    "ext/extconf.rb",
    "ext/go.bat",
    "ext/sparsehash-2.0.2/AUTHORS",
    "ext/sparsehash-2.0.2/COPYING",
    "ext/sparsehash-2.0.2/ChangeLog",
    "ext/sparsehash-2.0.2/INSTALL",
    "ext/sparsehash-2.0.2/Makefile.am",
    "ext/sparsehash-2.0.2/Makefile.in",
    "ext/sparsehash-2.0.2/NEWS",
    "ext/sparsehash-2.0.2/README",
    "ext/sparsehash-2.0.2/README_windows.txt",
    "ext/sparsehash-2.0.2/TODO",
    "ext/sparsehash-2.0.2/aclocal.m4",
    "ext/sparsehash-2.0.2/allocator.patch",
    "ext/sparsehash-2.0.2/config.guess",
    "ext/sparsehash-2.0.2/config.sub",
    "ext/sparsehash-2.0.2/configure",
    "ext/sparsehash-2.0.2/configure.ac",
    "ext/sparsehash-2.0.2/depcomp",
    "ext/sparsehash-2.0.2/doc/dense_hash_map.html",
    "ext/sparsehash-2.0.2/doc/dense_hash_set.html",
    "ext/sparsehash-2.0.2/doc/designstyle.css",
    "ext/sparsehash-2.0.2/doc/implementation.html",
    "ext/sparsehash-2.0.2/doc/index.html",
    "ext/sparsehash-2.0.2/doc/performance.html",
    "ext/sparsehash-2.0.2/doc/sparse_hash_map.html",
    "ext/sparsehash-2.0.2/doc/sparse_hash_set.html",
    "ext/sparsehash-2.0.2/doc/sparsetable.html",
    "ext/sparsehash-2.0.2/experimental/Makefile",
    "ext/sparsehash-2.0.2/experimental/README",
    "ext/sparsehash-2.0.2/experimental/example.c",
    "ext/sparsehash-2.0.2/experimental/libchash.c",
    "ext/sparsehash-2.0.2/experimental/libchash.h",
    "ext/sparsehash-2.0.2/install-sh",
    "ext/sparsehash-2.0.2/m4/acx_pthread.m4",
    "ext/sparsehash-2.0.2/m4/google_namespace.m4",
    "ext/sparsehash-2.0.2/m4/namespaces.m4",
    "ext/sparsehash-2.0.2/m4/stl_hash.m4",
    "ext/sparsehash-2.0.2/m4/stl_hash_fun.m4",
    "ext/sparsehash-2.0.2/missing",
    "ext/sparsehash-2.0.2/packages/deb.sh",
    "ext/sparsehash-2.0.2/packages/deb/README",
    "ext/sparsehash-2.0.2/packages/deb/changelog",
    "ext/sparsehash-2.0.2/packages/deb/compat",
    "ext/sparsehash-2.0.2/packages/deb/control",
    "ext/sparsehash-2.0.2/packages/deb/copyright",
    "ext/sparsehash-2.0.2/packages/deb/docs",
    "ext/sparsehash-2.0.2/packages/deb/rules",
    "ext/sparsehash-2.0.2/packages/deb/sparsehash.dirs",
    "ext/sparsehash-2.0.2/packages/deb/sparsehash.install",
    "ext/sparsehash-2.0.2/packages/rpm.sh",
    "ext/sparsehash-2.0.2/packages/rpm/rpm.spec",
    "ext/sparsehash-2.0.2/sparsehash.sln",
    "ext/sparsehash-2.0.2/src/config.h.in",
    "ext/sparsehash-2.0.2/src/config.h.include",
    "ext/sparsehash-2.0.2/src/google/dense_hash_map",
    "ext/sparsehash-2.0.2/src/google/dense_hash_set",
    "ext/sparsehash-2.0.2/src/google/sparse_hash_map",
    "ext/sparsehash-2.0.2/src/google/sparse_hash_set",
    "ext/sparsehash-2.0.2/src/google/sparsehash/densehashtable.h",
    "ext/sparsehash-2.0.2/src/google/sparsehash/hashtable-common.h",
    "ext/sparsehash-2.0.2/src/google/sparsehash/libc_allocator_with_realloc.h",
    "ext/sparsehash-2.0.2/src/google/sparsehash/sparsehashtable.h",
    "ext/sparsehash-2.0.2/src/google/sparsetable",
    "ext/sparsehash-2.0.2/src/google/template_util.h",
    "ext/sparsehash-2.0.2/src/google/type_traits.h",
    "ext/sparsehash-2.0.2/src/hash_test_interface.h",
    "ext/sparsehash-2.0.2/src/hashtable_test.cc",
    "ext/sparsehash-2.0.2/src/libc_allocator_with_realloc_test.cc",
    "ext/sparsehash-2.0.2/src/simple_compat_test.cc",
    "ext/sparsehash-2.0.2/src/simple_test.cc",
    "ext/sparsehash-2.0.2/src/sparsehash/dense_hash_map",
    "ext/sparsehash-2.0.2/src/sparsehash/dense_hash_set",
    "ext/sparsehash-2.0.2/src/sparsehash/internal/densehashtable.h",
    "ext/sparsehash-2.0.2/src/sparsehash/internal/hashtable-common.h",
    "ext/sparsehash-2.0.2/src/sparsehash/internal/libc_allocator_with_realloc.h",
    "ext/sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h",
    "ext/sparsehash-2.0.2/src/sparsehash/sparse_hash_map",
    "ext/sparsehash-2.0.2/src/sparsehash/sparse_hash_set",
    "ext/sparsehash-2.0.2/src/sparsehash/sparsetable",
    "ext/sparsehash-2.0.2/src/sparsehash/template_util.h",
    "ext/sparsehash-2.0.2/src/sparsehash/type_traits.h",
    "ext/sparsehash-2.0.2/src/sparsetable_unittest.cc",
    "ext/sparsehash-2.0.2/src/stamp-h1",
    "ext/sparsehash-2.0.2/src/template_util_unittest.cc",
    "ext/sparsehash-2.0.2/src/testutil.h",
    "ext/sparsehash-2.0.2/src/time_hash_map.cc",
    "ext/sparsehash-2.0.2/src/type_traits_unittest.cc",
    "ext/sparsehash-2.0.2/src/windows/config.h",
    "ext/sparsehash-2.0.2/src/windows/google/sparsehash/sparseconfig.h",
    "ext/sparsehash-2.0.2/src/windows/port.cc",
    "ext/sparsehash-2.0.2/src/windows/port.h",
    "ext/sparsehash-2.0.2/src/windows/sparsehash/internal/sparseconfig.h",
    "ext/sparsehash-2.0.2/vsprojects/hashtable_test/hashtable_test.vcproj",
    "ext/sparsehash-2.0.2/vsprojects/libc_allocator_with_realloc_test/libc_allocator_with_realloc_test.vcproj",
    "ext/sparsehash-2.0.2/vsprojects/simple_test/simple_test.vcproj",
    "ext/sparsehash-2.0.2/vsprojects/sparsetable_unittest/sparsetable_unittest.vcproj",
    "ext/sparsehash-2.0.2/vsprojects/time_hash_map/time_hash_map.vcproj",
    "ext/sparsehash-2.0.2/vsprojects/type_traits_unittest/type_traits_unittest.vcproj",
    "ext/spec.bat",
    "ext/template/google_hash.cpp.erb",
    "ext/template/main.cpp.erb",
    "google_hash.gemspec",
    "results.txt",
    "spec/bench_gc.rb",
    "spec/benchmark.rb",
    "spec/scale.rb",
    "spec/spec.google_hash.rb",
    "to_build_locally_run_ext_go_bat"
  ]
  s.homepage = "http://github.com/rdp/ruby_google_hash"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Ruby wrappers to the google hash library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sane>, [">= 0"])
      s.add_development_dependency(%q<hitimes>, [">= 0"])
    else
      s.add_dependency(%q<sane>, [">= 0"])
      s.add_dependency(%q<hitimes>, [">= 0"])
    end
  else
    s.add_dependency(%q<sane>, [">= 0"])
    s.add_dependency(%q<hitimes>, [">= 0"])
  end
end

